services:
  postgres:
    image: postgres:16-alpine
    container_name: securis-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: securis_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5431:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - securis-network

volumes:
  postgres_data:

networks:
  securis-network:
    driver: bridge
